### ISSUE TITLE
Spec for d-picture

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-d-picture#1]
0.0.1

Looks great, now hear at last is our spec, requesting removal of some of the goodies in that prototype :-(

Spec for d picture, component of esci web, Geoff, 17 Aug 2020

Follows zoom discussion with Bob, 14 Aug.

Simple, like d picture for ITNS, with only a couple of additions.
•	No X axis, no cursor
•	C and E curves, with the same SD, which is fixed.
•	Main bottom axis is ‘Cohen’s d’ and values shown from -3 to 7. Tick marks at 0.5 and 0.1 intervals.
•	C curve is fixed and centred on 0.
•	Mark C and E means with blue and red vertical lines, as at present.
•	Main slider below axis controls position of E curve, from 0 to 5. Nudge buttons at right hand end of slider. Slider controls values of d to two decimal places.
•	Slider could be sized and positioned so that its single handle runs from 0 to 5, under those values on the axis, so the handle always aligns under the mean of E.
•	Above the two curves show the value of d, as at present, always centred on the d interval, as at present. Shift this value up to give enough space for a thin black horizontal line segment extending between the two mean lines, with a small black short slanted line at each end, like ‘/’, perhaps at 45 degrees.
•	At left, a control panel for ‘Areas’ with three options, the first two as at present, and a third that is ‘Overlap’. Each has a checkbox, with ‘Shade?’ above the column of three checkboxes, as at present.
•	Let’s show the values of the areas all the while, not only when the corresponding Shade box is clicked on. Let’s have the areas as proportions (without leading zero) rather than %ages.
•	When an area is shaded, let’s show in the graph the value of the area, as at present, with colour of the numbers similar to the shading colour, as at present. Those values, in the graph: for the first two values (blue and red) can we have them positioned further out—at the current height above the axis but the blue value out near the left border of the blue area, the red value out near the right (but never going off screen to the right). If possible!
•	When both E above mean C, and C below mean E, are clicked on, it’s great to have the overlap in a purple that is as close as possible to a sum of the red and blue colours. But the total overlap area should be shaded, not just that between the means. The purple should appear whenever both those two areas are clicked on.
•	The third area to be reported is overlap. Calculate this as twice the area to the right of d/2 under a normal distribution that has mean 0 and SD = 1 (i.e. same as SD of C and E).
•	If ‘Overlap’ is clicked on, for the overlap area to be shaded it needs to be marked in some way that can work whether the other two areas are both on, either on, or both off. Would it be feasible to have it a solid colour of deeper purple? Or dotted purple? Or cross-hatched with fine black lines? Or…?
•	A separate small panel at left that displays the ‘Probability of superiority’, which is the probability that a randomly chosen value of E is greater than a randomly chosen value of C. No checkbox needed: display this value all the while. Calculate as the area to the left of d in a normal distribution having mean zero and SD = SQRT(2), where SD of C and E curves is 1.
•	A separate small panel headed ‘N required for sufficient precision’ that reports the N needed, in an independent groups experiment with each group of size N, to obtain, on average, a margin of error (MoE, half the length of the 95% CI) that is d/2. Show this value all the while, no checkbox needed. When d = 0, show value as a dash. When d is very small, we need some graceful way for N to get very large, without running off screen or crashing something. Probably not scientific notation (i.e., with a value of the exponent of 10). Perhaps large values are shown as ‘>10,000’?
•	That N = (30.73 / d^2), rounded up to the next integer. We’re assuming sigma is known, so we use z. (That weird number comes from 1.96, critical value of z for 95% CI.
•	I'll make a spec for tips after the next round.

**Comment by gfmoore** [comment]
Done it all!!!!!!  I know, wow!!  Well I've got nothing else to do.

Okay, I'm sure there will the undoubted tweaks...

Couple of thoughts. I've done probabilities to 4dp?

I did a solid colour of deep(er) purple - who by coincidence have released a new album Whoosh. It's rockin!!! Ahh my youth!

For N I rounded up (called ceiling in JavasScript) so 3.2 goes to 4.

It was actually quite tricky to position the d slider - let me know if you think it needs any further adjustment - oh, okay, tweaks

N = 30.73/d2 I read as 30.73/d^2   (d squared).

You were right to make this spec as a complete document, but can we now have one issue per problem please. It's easier for me to control :)

**Comment by gdcumming** [comment]
0.2.6

Done! Great! Closing!
