### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-d-picture#10]
0.2.5

Panel 1.
1 Areas: 'See area values and control area shading'
Shade?: 'Click to shade areas under curves'
Area of E above mean of C <value> [ ]: 'Shaded red'
Area of C below mean of E <value> [ ]: 'Shaded blue'
Overlap         <value> [ ]: 'Shaded purple'

Panel 2
2 Probability of superiority <value>: 'Probability that a randomly chosen value from E is greater than a randomly chosen value from C'

Panel 3
3 _N_ required for sufficient precision <value>: 'Two independent groups, each of size _N_, will give a 95% CI on the difference between the means with MoE = _d_/2. I.e. CI length = _d_. Calculated _N_ is rounded up to the next integer.'

**Comment by gfmoore** [comment]
Done

**Comment by gdcumming** [comment]
0.2.6

Looks good, closing
