### ISSUE TITLE
Control panel design

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-d-picture#3]
0.2.1

A few tweaks please:

--a bit more vertical space, esp. for 2 and 3. Looks a bit cramped.

--Panel headings (and numbers) not bold. Font sizes a bit bigger, and a bit bigger still for headings, as in **distributions**.

--Panel 3: 'N' _italic_ (but E and C not italic)

--Lower case 'S' in 'Probability of superiority'

**Comment by gfmoore** [comment]
Done, you were right the font was a tad smaller, not sure how that happened as I copied the code!
