### ISSUE TITLE
Area values in graph

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-d-picture#4]
0.2.1

For each of the three areas, display the area value in the graph only when that area is clicked ON. (Colours are good.)

In particular, display overlap area value only when Overlap is clicked on.

It's good to have each value in a white rectangle. Can that rectangle be a tiny bit smaller, and the value centred within the rectangle both horizontally and vertically? 

I find I need to adjust the display H and V ratio on my screen (drag the lower and right hand edges of the whole window) to get a figure that will look best on a book page--mainly by shifting the bottom edge up so curves are not too narrow and high. (I appreciate that details of my screen dictate how the graph looks. It's great that the right hand display panel automatically adjusts to fit the window. Very nice.)

When I move the bottom edge up, the area values shift in their white rectangles, touching the top and left edges. They can even shift up so that parts of the numbers appear above those rectangles.

**Comment by gfmoore** [comment]
Ahh my bad, I understood the phrase "Let’s show the **values of the areas all the while**, not only when the corresponding Shade box is clicked on. " to mean all the area values in the panel not the areas on the graph, and now I read the second paragraph. I thought it didn't make sense.

Anyway reverted back to what I thought it should be.


As for positioning, yes I've now adjusted this to match with the curve height, so should work better now, including d value and line

**Comment by gdcumming** [comment]
0.2.5

Sorry about the ambiguity in the spec. This all looks great :-)
