### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-d-picture#6]
0.2.1

This is good, and well positioned.

Let's have 'Cohen's _d_' a little larger, and a tiny bit lower if possible, say to sit on a line extending the grey slider bar.

**Comment by gfmoore** [comment]
How's that. I hope you don't ask to move it left as the positioning of this and the slider is really tricky in order to make everything line up - can it satisfice?

**Comment by gdcumming** [comment]
0.2.5

Great
