### ISSUE TITLE
Position of d value and line segment in graph

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-d-picture#7]
0.2.1

The 'd = value' and the line segment just below it are generally fine and often sit in a good position just above the curves.

But if I need to drag the bottom edge of the window up, the value and segment remain fixed relative to the top edge of the display, whereas the top of the curves shift up. Soon the value and segment can be tangled up in the curves and mean lines, and even lost behind shaded areas.

There always looks to be a bit of space above the curves. Could the d value and line segment shift upwards, so it always sits a little above the curves? (If not possible or practical, a second best would be to bring it to the front of all shading, and even the red and blue lines of the distributions themselves.)

**Comment by gfmoore** [comment]
Fixed this (possibly) when adjusting area labels. How does it look now. (No new version)

**Comment by gdcumming** [comment]
0.2.5

Looks good
