### ISSUE TITLE
Change N reporting

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-d-picture#8]
0.2.5

A change of mind please, Panel 3.

Let's have the full value of N reported in every case. I think it's around 320,000 for our smallest d value, d = .01, and that would easily fit in the available space.

**Comment by gfmoore** [comment]
It says 307200  is that correct? Done anyway.

**Comment by gdcumming** [comment]
0.2.6

d=0.1 is correctly reported as 307300 or 307301--seems to vary a bit, depending on whether click d up or down to get to 0.1. Similar tiny variation for other very small d values. Doesn't matter, we don't care! Closing.
